# Generated by Django 4.1.3 on 2022-11-19 13:53

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Процессор')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=127, verbose_name='Название телефона')),
                ('roarCam', models.CharField(default=None, max_length=31, verbose_name='Задняя камера')),
                ('frontCam', models.CharField(default=None, max_length=31, verbose_name='Фронтальная камера')),
                ('mem1', models.CharField(default=0, max_length=31, verbose_name='Объем памяти 1')),
                ('price_1', models.CharField(default=0, max_length=127, verbose_name='Цена 1')),
                ('mem2', models.CharField(blank=True, default=0, max_length=31, null=True, verbose_name='Объем памяти 2')),
                ('price_2', models.CharField(blank=True, default=0, max_length=127, null=True, verbose_name='Цена 2')),
                ('mem3', models.CharField(blank=True, default=0, max_length=31, null=True, verbose_name='Объем памяти 3')),
                ('price_3', models.CharField(blank=True, default=0, max_length=127, null=True, verbose_name='Цена 3')),
                ('mem5', models.CharField(blank=True, default=0, max_length=31, null=True, verbose_name='Объем памяти 4')),
                ('price_4', models.CharField(blank=True, default=0, max_length=127, null=True, verbose_name='Цена 4')),
                ('mem4', models.CharField(blank=True, default=0, max_length=31, null=True, verbose_name='Объем памяти 5')),
                ('price_5', models.CharField(blank=True, default=0, max_length=127, null=True, verbose_name='Цена 5')),
                ('color_name1', models.CharField(default=None, max_length=31, verbose_name='Наименование цвета 1')),
                ('image1', models.ImageField(default=None, upload_to='', verbose_name='Изображение 1')),
                ('color1', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('color_name2', models.CharField(blank=True, default=None, max_length=31, null=True, verbose_name='Наименование цвета 2')),
                ('image2', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 2')),
                ('color2', colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None)),
                ('color_name3', models.CharField(blank=True, default=None, max_length=31, null=True, verbose_name='Наименование цвета 3')),
                ('image3', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 3')),
                ('color3', colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None)),
                ('color_name4', models.CharField(blank=True, default=None, max_length=31, null=True, verbose_name='Наименование цвета 4')),
                ('image4', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 4')),
                ('color4', colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None)),
                ('color_name5', models.CharField(blank=True, default=None, max_length=31, null=True, verbose_name='Наименование цвета 5')),
                ('image5', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 5')),
                ('color5', colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None)),
                ('description', models.TextField(default=None, max_length=255, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=127, verbose_name='Подборка')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('hookid', models.CharField(blank=True, default=None, max_length=31, null=True, verbose_name='Якорь')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.compilation')),
                ('publications', models.ManyToManyField(related_name='PUBLICATIONS', to='main.product', verbose_name='dadew')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
