# Generated by Django 4.1.3 on 2022-11-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilation',
            name='level',
        ),
        migrations.RemoveField(
            model_name='compilation',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='compilation',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='compilation',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='compilation',
            name='tree_id',
        ),
    ]
