# Generated by Django 4.1.3 on 2022-11-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Подборка')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Rom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='Память')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=127, verbose_name='Название телефона')),
                ('price', models.CharField(max_length=127, verbose_name='Цена')),
                ('compilations', models.ManyToManyField(to='main.compilation', verbose_name='Участие в подборках')),
            ],
        ),
    ]
