# Generated by Django 4.1.3 on 2022-11-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_review_book_remove_product_price_product_mem1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Изображение'),
        ),
    ]
