# Generated by Django 4.1.3 on 2022-11-14 12:06

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_image_product_color1_product_color2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rom',
        ),
        migrations.AddField(
            model_name='compilation',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.cpu'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=None, max_length=255, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='frontCam',
            field=models.CharField(default=None, max_length=31, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='main.manufacter'),
        ),
        migrations.AddField(
            model_name='product',
            name='roarCam',
            field=models.CharField(default=None, max_length=31, verbose_name='Задняя камера'),
        ),
        migrations.AlterField(
            model_name='compilation',
            name='name',
            field=models.CharField(default=None, max_length=127, verbose_name='Подборка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color1',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='color2',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='color3',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='color4',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='color5',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
