# Generated by Django 4.1.3 on 2022-11-14 12:25

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_rom_compilation_color_product_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color2',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='color3',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='color4',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='color5',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name2',
            field=models.CharField(default=None, max_length=31, null=True, verbose_name='Наименование цвета 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name3',
            field=models.CharField(default=None, max_length=31, null=True, verbose_name='Наименование цвета 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name4',
            field=models.CharField(default=None, max_length=31, null=True, verbose_name='Наименование цвета 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name5',
            field=models.CharField(default=None, max_length=31, null=True, verbose_name='Наименование цвета 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Изображение 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Изображение 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mem2',
            field=models.CharField(default=0, max_length=31, null=True, verbose_name='Объем памяти 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mem3',
            field=models.CharField(default=0, max_length=31, null=True, verbose_name='Объем памяти 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mem4',
            field=models.CharField(default=0, max_length=31, null=True, verbose_name='Объем памяти 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mem5',
            field=models.CharField(default=0, max_length=31, null=True, verbose_name='Объем памяти 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_2',
            field=models.CharField(default=0, max_length=127, null=True, verbose_name='Цена 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_3',
            field=models.CharField(default=0, max_length=127, null=True, verbose_name='Цена 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_4',
            field=models.CharField(default=0, max_length=127, null=True, verbose_name='Цена 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_5',
            field=models.CharField(default=0, max_length=127, null=True, verbose_name='Цена 5'),
        ),
    ]
