# Generated by Django 4.1.3 on 2022-11-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_color2_alter_product_color3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_name2',
            field=models.CharField(blank=True, default=None, max_length=31, null=True, verbose_name='Наименование цвета 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name3',
            field=models.CharField(blank=True, default=None, max_length=31, null=True, verbose_name='Наименование цвета 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name4',
            field=models.CharField(blank=True, default=None, max_length=31, null=True, verbose_name='Наименование цвета 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name5',
            field=models.CharField(blank=True, default=None, max_length=31, null=True, verbose_name='Наименование цвета 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mem2',
            field=models.CharField(blank=True, default=0, max_length=31, null=True, verbose_name='Объем памяти 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mem3',
            field=models.CharField(blank=True, default=0, max_length=31, null=True, verbose_name='Объем памяти 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mem4',
            field=models.CharField(blank=True, default=0, max_length=31, null=True, verbose_name='Объем памяти 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mem5',
            field=models.CharField(blank=True, default=0, max_length=31, null=True, verbose_name='Объем памяти 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_2',
            field=models.CharField(blank=True, default=0, max_length=127, null=True, verbose_name='Цена 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_3',
            field=models.CharField(blank=True, default=0, max_length=127, null=True, verbose_name='Цена 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_4',
            field=models.CharField(blank=True, default=0, max_length=127, null=True, verbose_name='Цена 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_5',
            field=models.CharField(blank=True, default=0, max_length=127, null=True, verbose_name='Цена 5'),
        ),
    ]
